export const ACTION_INSERT_TODO = 'ACTION_INSERT_TODO';
export const ACTION_DELETE_TODO = 'ACTION_DELETE_TODO';
export const ACTION_EDIT_BEGIN = 'ACTION_EDIT_BEGIN';
export const ACTION_EDIT_END = 'ACTION_EDIT_END';